version: "3.9"

services:
  backend:
    build: ./backend
    container_name: marketnews-backend
    env_file: .env
    expose:
      - "8000"
    networks:
      - appnet

  frontend:
    build: ./frontend
    container_name: marketnews-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
