# version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: marketnews-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8000}
    container_name: marketnews-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
